### ISSUE TITLE
progress 中 的动画 panoramic 是不是忘了加上去？

### ISSUE THREAD

**Issue by catchonme** [l-hammer/You-need-to-know-css#59]
在 [滚动条](https://lhammer.cn/You-need-to-know-css/#/stripes-background?id=%E8%BF%9B%E5%BA%A6%E6%9D%A1) 中，类`progress-bg`的`animation: panoramic 20s linear infinite;` 中的 `panoramic` 作者是忘了贴代码吗？

**Comment by l-hammer** [comment]
@catchonme 已fixed，因为@keyframes在markdown中不生效，都写在了[animation](https://github.com/l-hammer/You-need-to-know-css/blob/master/assets/index.css#L42)，有一些确实忘给加了~ 感谢提醒~

**Comment by catchonme** [comment]
好的，非常感谢
